import { createImportFnTests } from '@bemedev/dev-utils/build-tests';

describe(
  ...createImportFnTests({
    path: 'extensions/booleans',
    SUCCESS: ['toggle', 'toNumber'],
    FAILS: [
      'identity',
      'isValue',
      'isNotValue',
      'voidAction',
      'tap',
      'flatten',
      'mapArray',
      'monad',
      'toggleMonad',
      'operation',
      'addBy',
      'timesBy',
      'divisionBy',
      'moduloBy',
      'exponentBy',
      'multiplyBy',
      'isZero',
      'isNotZero',
      'compare',
      'sign',
      'toUpperCase',
      'toLowerCase',
      'trim',
      'capitalize',
      'escapeRegExp',
      'replaceAll',
      'concat',
    ],
  }),
);
